// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAudio.Data;

#nullable disable

namespace WebAudio.Migrations
{
    [DbContext(typeof(WebAudioDbContext))]
    [Migration("20240329102112_NumberOfRequestFile")]
    partial class NumberOfRequestFile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("WebAudio.Entities.NoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("End")
                        .HasColumnType("REAL");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<float?>("Start")
                        .HasColumnType("REAL");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text_norm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ThoiGianCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NoiDungs");
                });

            modelBuilder.Entity("WebAudio.Entities.NumberOfRequestFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberRequestFile")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NumberOfRequestFiles");
                });

            modelBuilder.Entity("WebAudio.Entities.QuanLyFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateToFile")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ThoiGianCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QuanLyFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
